apiVersion: v1
kind: Service
metadata:
  name: trocopoints-api
  namespace: trocopoints
spec:
  type: NodePort
  selector:
    app: trocopoints-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
