apiVersion: v1
kind: Secret
metadata:
  name: trocopoints-api-secret
  namespace: trocopoints
type: Opaque
stringData:
  ConnectionStrings__OracleConnectionString: "User Id=trocopoints;Password=TrocoPoints123;Data Source=host.docker.internal:1521/XEPDB1;"
  MongoDb__ConnectionString: "mongodb://trocopoints:TrocoPoints123@host.docker.internal:27017/?authSource=admin"
  Redis__Configuration: "host.docker.internal:6379,password=TrocoPoints123"
