<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrocoPoints.Domain\TrocoPoints.Domain.csproj" />
    <ProjectReference Include="..\TrocoPoints.Application\TrocoPoints.Application.csproj" />
    <ProjectReference Include="..\TrocoPoints.Infrastructure\TrocoPoints.Infrastructure.csproj" />
  </ItemGroup>

</Project>
